language: node_js

notifications:
  email:
    on_success: always
    on_failure: always

install:
  - npm install -g codecov

script:
  - npm install
  - npm run test

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js # publish coverage info to coveralls
